py_test(
    	name = "TestMain",
	srcs = ["TestMain.py"],
	deps = [
		"//src/core:libPepData",
		"//src/core:libPepPars",
		"//src/core:libPepGen",
		"//src/exe:PepMain",
	],
	data = ["//test/cases"],
)
