py_library(
	name = "libPepData",
	srcs = ["libPepData.py"],
	visibility = ["//visibility:public"],
)

py_library(
	name = "libPepPars",
	srcs = ["libPepPars.py"],
	visibility = ["//visibility:public"],
)

py_library(
	name = "libPepGen",
	srcs = ["libPepGen.py"],
	visibility = ["//visibility:public"],
)
